#!/usr/bin/env ruby
# frozen_string_literal: true

require "open3"

root = File.expand_path("..", __dir__)
test_files = Dir[File.join(root, "test", "*_test.rb")].sort

runner = "ARGV.each { |path| require path }"
command = [RbConfig.ruby, "-I#{File.join(root, "lib")}", "-I#{File.join(root, "test")}", "-e", runner] + test_files
stdout, stderr, status = Open3.capture3(*command)

print stdout
warn stderr unless stderr.empty?
exit status.exitstatus
